apiVersion: batch/v1
kind: Job
metadata:
  name: do-algo-deploy
  labels:
    app: do-algo
spec:
  backoffLimit: 2
  template:
    metadata:
      labels:
        app: do-algo
    spec:
      containers:
      - name: do-algo
        image: danackerson/algo_vpn:{{CIRCLE_BUILD_NUM}}
        env:
        - name: region
          valueFrom:
            secretKeyRef:
              name: algo-env-secrets
              key: REGION
        - name: doToken
          valueFrom:
            secretKeyRef:
              name: algo-env-secrets
              key: digitalOceanToken
        - name: slackToken
          valueFrom:
            secretKeyRef:
              name: algo-env-secrets
              key: SLACK_TOKEN
      imagePullSecrets:
      - name: dockerhub-creds
      restartPolicy: Never
